services:
  db:
    image: postgres:16-alpine
    container_name: uk_web_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      POSTGRES_DB: uk_web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: uk_web_server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: uk_web_client
    restart: always
    ports:
      - "3000:80"       # Тот самый порт 3000, на который завязан твой Nginx!
    depends_on:
      - server

volumes:
  postgres_data: