name: Deploy Application

on:
  push:
    branches: [ "main" ] # Запускать при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/uk_web
            git pull origin main
            
            # 1. Останавливаем контейнеры
            docker compose down
            
            # 2. Безопасно чистим старые образы и кэш (БЕЗ флага --volumes!)
            docker system prune -af
            
            # 3. Собираем бэкенд и чистим кэш сборки
            docker compose build server
            docker builder prune -f
            
            # 4. Собираем фронтенд и чистим кэш сборки
            docker compose build --no-cache client
            docker builder prune -f
            
            # 5. Поднимаем всё из готовых образов
            docker compose up -d
            
            # 6. Финальная подчистка неиспользуемых временных образов
            docker image prune -f